### ISSUE TITLE
Getting OpenSSL::Cipher::CipherError 

### ISSUE THREAD

**Issue by ayza-hamid** [tinfoil/devise-two-factor#160] opened 2019-10-25 10:55 UTC
### While trying to login in I am getting this error, after updating the version of rails and ruby.

> devise :recoverable, :rememberable, :trackable, :validatable, :two_factor_backupable, :two_factor_authenticatable, otp_secret_encryption_key: APP_CONFIG[:otp_encryption_key]

I tried changing the otp secret encryption key, but I was still unable to **reindex the Models**.

Anyone faced the similar issue?

```**OpenSSL::Cipher::CipherError ():**
  
encryptor (3.0.0) lib/encryptor.rb:98:in `final'
encryptor (3.0.0) lib/encryptor.rb:98:in `crypt'
encryptor (3.0.0) lib/encryptor.rb:49:in `decrypt'
attr_encrypted (3.1.0) lib/attr_encrypted.rb:240:in `decrypt'
attr_encrypted (3.1.0) lib/attr_encrypted.rb:329:in `decrypt'
attr_encrypted (3.1.0) lib/attr_encrypted.rb:161:in `block (2 levels) in attr_encrypted'
activemodel (6.0.0) lib/active_model/serialization.rb:137:in `block in serializable_hash'
activemodel (6.0.0) lib/active_model/serialization.rb:137:in `each'
activemodel (6.0.0) lib/active_model/serialization.rb:137:in `serializable_hash'
activerecord (6.0.0) lib/active_record/serialization.rb:19:in `serializable_hash'
devise (4.7.1) lib/devise/models/authenticatable.rb:115:in `serializable_hash'
searchkick (3.1.1) lib/searchkick/model.rb:86:in `search_data'
searchkick (3.1.1) lib/searchkick/record_data.rb:52:in `search_data'
searchkick (3.1.1) lib/searchkick/record_data.rb:14:in `index_data'
searchkick (3.1.1) lib/searchkick/bulk_indexer.rb:43:in `block in bulk_index'
searchkick (3.1.1) lib/searchkick/bulk_indexer.rb:43:in `map'
searchkick (3.1.1) lib/searchkick/bulk_indexer.rb:43:in `bulk_index'
searchkick (3.1.1) lib/searchkick/index.rb:125:in `store'
searchkick (3.1.1) lib/searchkick/logging.rb:28:in `block in store'
activesupport (6.0.0) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.0) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.0) lib/active_support/notifications.rb:180:in `instrument'
searchkick (3.1.1) lib/searchkick/logging.rb:27:in `store'
searchkick (3.1.1) lib/searchkick/record_indexer.rb:54:in `reindex_record'
searchkick (3.1.1) lib/searchkick/record_indexer.rb:35:in `reindex'
searchkick (3.1.1) lib/searchkick/model.rb:78:in `reindex'
activesupport (6.0.0) lib/active_support/callbacks.rb:429:in `block in make_lambda'
activesupport (6.0.0) lib/active_support/callbacks.rb:264:in `block in conditional'
activesupport (6.0.0) lib/active_support/callbacks.rb:518:in `block in invoke_after'
activesupport (6.0.0) lib/active_support/callbacks.rb:518:in `each'
activesupport (6.0.0) lib/active_support/callbacks.rb:518:in `invoke_after'
activesupport (6.0.0) lib/active_support/callbacks.rb:136:in `run_callbacks'
activesupport (6.0.0) lib/active_support/callbacks.rb:827:in `_run_commit_callbacks'
activerecord (6.0.0) lib/active_record/transactions.rb:339:in `committed!'
activerecord (6.0.0) lib/active_record/connection_adapters/abstract/transaction.rb:127:in `commit_records'
activerecord (6.0.0) lib/active_record/connection_adapters/abstract/transaction.rb:265:in `block in commit_transaction'
/home/square63/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
activerecord (6.0.0) lib/active_record/connection_adapters/abstract/transaction.rb:255:in `commit_transaction'
activerecord (6.0.0) lib/active_record/connection_adapters/abstract/transaction.rb:293:in `block in within_new_transaction'
/home/square63/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
activerecord (6.0.0) lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
activerecord (6.0.0) lib/active_record/connection_adapters/abstract/database_statements.rb:277:in `transaction'
activerecord (6.0.0) lib/active_record/transactions.rb:212:in `transaction'
````

**Comment by skycocker** [comment] 2019-10-30 03:08
Similar here. Investigating whether it's caused by my own changes - doesn't seem like so at first sight, though.

**Comment by skycocker** [comment] 2019-11-06 02:27
@ayza-hamid not sure about your exact case, but it was my fault for me. The issue is that after you change the key (and in fact I did that) you also have to reset each user's `otp_`-related DB fields, essentially resetting their 2fa setup. If that helps you too then I guess we can close it.

**Comment by ayza-hamid** [comment] 2019-11-07 05:14
The issue was with the User records. May be they were encrypted with different key and I was trying to decrypt it with some different key.

**Comment by skycocker** [comment] 2019-11-07 13:19
Glad you got this fixed. I think you could close the issue for now.

**Closed** 2019-11-08 04:04 UTC
